# Mapping of sports to COCO class IDs
# 0: person, 32: sports ball, 34: baseball bat, 35: baseball glove, 
# 36: skateboard, 37: surfboard, 38: tennis racket

football:
  classes: [0, 32]
  label: "Football"

basketball:
  classes: [0, 32]
  label: "Basketball"

cricket:
  classes: [0, 32, 34]
  label: "Cricket"

racing:
  classes: [0, 2, 3, 7] # person, car, motorcycle, truck
  label: "Racing"

general:
  classes: [0]
  label: "General"